homepage:
    path: /
    controller: Controllers\Default
    action: index
authenticate:
    path: /auth
    controller: Controllers\Auth
    action: index
slash_command:
    path: /command
    controller: Controllers\SlashCommand
    action: index